import { Book } from './types';

export const BOOKS: Book[] = [
  {
    id: '1',
    title: 'Indian Polity',
    author: 'M. Laxmikanth',
    price: 750,
    originalPrice: 995,
    category: 'Competitive Exams',
    description: 'The bible for UPSC aspirants regarding Indian Polity and Constitution.',
    image: 'https://logicwork.in/wp-content/uploads/2022/07/Indian-Polity-by-M-Laxmikant.jpeg',
    rating: 5,
    publisher: 'McGraw Hill',
    language: 'English',
    inStock: true
  },
  {
    id: '2',
    title: 'Introduction to the Constitution of India',
    author: 'D.D. Basu',
    price: 450,
    originalPrice: 550,
    category: 'Competitive Exams',
    description: 'A comprehensive analytical study of the Constitution of India.',
    image: 'https://rukminim1.flixcart.com/image/832/832/k5wse4w0/book/7/2/8/introduction-to-constitution-of-india-23rd-edition-dd-basu-original-imafzhfsqzzhmvqg.jpeg?q=70',
    rating: 4.5,
    publisher: 'LexisNexis',
    language: 'English',
    inStock: true
  },
  {
    id: '3',
    title: 'A Brief History of Modern India',
    author: 'Rajiv Ahir',
    price: 380,
    originalPrice: 485,
    category: 'Competitive Exams',
    description: 'Spectrum Books covers the history of modern India in a concise manner.',
    image: 'https://django-order-files.s3.amazonaws.com/shop/images/IMG_7613.jpeg',
    rating: 4.8,
    publisher: 'Spectrum Books',
    language: 'English',
    inStock: true
  },
  {
    id: '4',
    title: 'India\'s Ancient Past',
    author: 'R.S. Sharma',
    price: 290,
    originalPrice: 350,
    category: 'Competitive Exams',
    description: 'A classic text on Ancient Indian history.',
    image: 'https://www.bookwalas.com/wp-content/uploads/2023/06/71QV6g38FdL.jpg',
    rating: 4.2,
    publisher: 'Oxford University Press',
    language: 'English',
    inStock: true
  },
  {
    id: '5',
    title: 'Certificate Physical and Human Geography',
    author: 'G.C. Leong',
    price: 310,
    originalPrice: 395,
    category: 'Competitive Exams',
    description: 'Essential for physical geography concepts.',
    image: 'https://dms.mydukaan.io/original/jpeg/upload_file_service/840cb13d-c4c6-45f2-84cc-6ada0a0ff889/whatsapp-image-2022-12-23-at-1-27-09-pm.jpeg',
    rating: 4.7,
    publisher: 'Oxford',
    language: 'English',
    inStock: true
  },
  {
    id: '6',
    title: 'Indian Art and Culture',
    author: 'Nitin Singhania',
    price: 650,
    originalPrice: 850,
    category: 'Competitive Exams',
    description: 'Comprehensive guide for Indian Art and Culture for Civil Services.',
    image: 'https://wishallbook.com/wp-content/uploads/2020/07/Indian-Art-and-Culture-Nitin-Singhania-for-Civil-Services-2020-Latest-Edition-1534x2048.jpg',
    rating: 4.9,
    publisher: 'McGraw Hill',
    language: 'English',
    inStock: true
  },
  {
    id: '7',
    title: 'Environment',
    author: 'Shankar IAS',
    price: 520,
    originalPrice: 650,
    category: 'Competitive Exams',
    description: 'Complete guide on Environment and Ecology.',
    image: 'https://typof.co/stores/6748/Cnokl0Q7q8rWBImz.webp',
    rating: 4.6,
    publisher: 'Shankar IAS Academy',
    language: 'English',
    inStock: true
  },
  {
    id: '8',
    title: 'Oxford Student Atlas for India',
    author: 'Oxford',
    price: 250,
    originalPrice: 325,
    category: 'Reference',
    description: 'Latest maps and data for students.',
    image: 'https://m.media-amazon.com/images/I/51BsGXjzx8L.jpg',
    rating: 4.5,
    publisher: 'Oxford',
    language: 'English',
    inStock: true
  },
  {
    id: '9',
    title: 'NCERT Science Set (Class 6-10)',
    author: 'NCERT',
    price: 450,
    category: 'School',
    description: 'Foundation science books for school and competitive exams.',
    image: 'https://m.media-amazon.com/images/I/91gcjeazhvL.jpg',
    rating: 5,
    publisher: 'NCERT',
    language: 'English',
    inStock: true
  },
  {
    id: '10',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    price: 250,
    originalPrice: 350,
    category: 'Novels',
    description: 'A story about following your dreams.',
    image: 'https://i.thenile.io/r1000/9780061233845.jpg?r=5f5c0b15edb84',
    rating: 4.5,
    publisher: 'HarperCollins',
    language: 'English',
    inStock: true
  },
  {
    id: '11',
    title: 'Classmate Notebooks (Pack of 6)',
    author: 'ITC',
    price: 300,
    category: 'Stationery',
    description: 'High quality ruled paper.',
    image: 'https://m.media-amazon.com/images/I/61hyWg9xWXL._AC_SS450_.jpg',
    rating: 4.8,
    publisher: 'ITC',
    language: 'N/A',
    inStock: true
  }
];

export const TESTIMONIALS = [
  { id: 1, name: "Rahul S.", text: "Best shop for UPSC books in Sarita Vihar. Found all Spectrum series here.", role: "Student" },
  { id: 2, name: "Priya M.", text: "Very fast delivery and the books were in perfect condition. Highly recommended!", role: "College Student" },
  { id: 3, name: "Amit K.", text: "Raj Kumar ji is very helpful. He arranged a rare geography book for me in 2 days.", role: "Teacher" },
];